#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libsvn-dev /usr/share/doc/libsvn1 1.10.3-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.5.3
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/libsvn-dev /usr/share/doc/libsvn1 1.10.3-1\~ -- "$@"
# End automatically added section
